"""Render evidence with explicit limitations; does not touch production."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'data/audits/critical_rejection_v6.3'
def main():
    d=json.loads((OUT/'research.json').read_text(encoding='utf8'));a=json.loads((OUT/'archive_evidence.json').read_text(encoding='utf8'))
    c=d['cohort'];r=d['reference'];s=d['scores'];m=d['mtf']
    l=json.loads((OUT/'liquidity_1623_summary.json').read_text(encoding='utf8'))
    l362=json.loads((OUT/'liquidity_362_summary.json').read_text(encoding='utf8'))
    diff=json.loads((OUT/'actual_detector_diff_summary.json').read_text(encoding='utf8'))
    v64_path=ROOT/'data/audits/v64_success_comparison/summary.json'
    v64=json.loads(v64_path.read_text(encoding='utf8')) if v64_path.exists() else {}
    lines=['# Критическое исследование V6.3 — исправление доказательств',
    '', '## ROOT CAUSE', '',
    'Предыдущий отчёт содержал ошибки агрегации. Его waterfall, FIRST BLOCKER и утверждение о 96,55% потерь нельзя использовать для принятия решений. Терминальная причина не является первым отказом за жизнь сетапа. Смешивались последние checks, любые отказы за всю историю и ever-entry. Все 18 entry-кандидатов ошибочно имели Rejection FAIL в той таблице.',
    f"Исходная база: {a['cohort']} ID; rejection когда-либо PASS={a['rejection_ever']['PASS']}, FAIL={a['rejection_ever']['FAIL']}, ещё не достигнут={a['rejection_ever']['NOT_REACHED']}, UNKNOWN={a['rejection_ever']['UNKNOWN']}. Эти множества пересекаются во времени; складывать их нельзя.",
    'Валидатор записывает первый отказ конкретного вызова. Записи после rejection доказывают его прохождение; отсутствие записи не доказывает PASS. Полные события и политики сохранены в archive_evidence.json.',
    f"V6.4 same-engine comparison: {v64}. Полная synthetic карточка: data/audits/v64_success_comparison/REFERENCE_SUCCESS_CASE.json; real18_cards.json и real18_timelines.json содержат одинаковые поля и causal time series. Historical execution context частично заменён явно помеченными mock book/funding/market данными; это не backtest.",
    '', '## REJECTION AUDIT', '',
    'trading/strategy.py: validate_signal. Берётся последняя строка уже закрытого отсортированного DataFrame. LONG: C[T] > O[T] AND C[T] >= CE. SHORT: C[T] < O[T] AND C[T] <= CE. Равенство close/open не проходит; равенство close/CE проходит.',
    'До реакции требуется хотя бы один бар j в последних retest_window_bars с low[j] <= top AND high[j] >= bottom AND timestamp[j] > formed_at. balanced/contextual используют окно; legacy — один бар. contextual дополнительно допускает continuation при age<=2, но проверяет breakout/regime/relative-volume позже. Переменная rejection хранит последнюю touching candle для SL, но цвет и CE проверяются у последней свечи T, которая может отличаться от touching candle.',
    'Wick ratio, engulfing, displacement и MSS не входят в production-AND реакции. Они измеряются только исследовательскими вариантами. Неверно говорить о 99,9% отказов detector по прежней таблице.',
    'На входе engine вызывает decision_candles: сырой порядок/дубликаты/пропуски валидируются, затем остаются свечи с open_timestamp+duration<=observed_at. Структурный pivot получает правые бары только после их закрытия. validate_signal сам по себе не проверяет wall clock — гарантия находится в вызывающем коде. Индексы i+1 в FVG являются барами внутри уже известного префикса, не будущим относительно решения. Хранить timestamp открытия и время решения следует отдельно.',
    f"Из прежнего набора 1610 восстановлены {c['modes']['A']['covered']} ID с закрытыми OHLC-префиксами. Остальные — UNKNOWN, не FAIL. Всего по 1654 покрыты {c['covered']}.",
    '', '| Reaction | Count | Production PASS | FAIL | N/A |','|---|---:|---:|---:|---:|']
    for k,v in c['reaction_matrix'].items():lines.append(f"| {k} | {v.get('count',0)} | {v.get('PASS',0)} | {v.get('FAIL',0)} | {v.get('N/A',0)} |")
    lines += ['', 'Count — уникальный ID хотя бы с одним признаком; PASS приоритетен, если на одном из таких баров пройдена реакция. N/A — зона уже инвалидирована или нет актуального ретеста. Wick: touching candle, directional wick/range>=0.4, close за CE; body: directional close за CE; close_ce: пересечение CE относительно предыдущего close; engulfing: поглощение тела противоположной свечи; displacement: направленное тело>=предыдущий ATR14; MSS: новое CHOCH относительно прошлого префикса. Multiple — минимум два признака.',
    '', '| Mode | Passed reaction+retest+validity | Technical proxy без полного market context | Potential | Confirmed |','|---|---:|---:|---|---|']
    for key,v in c['modes'].items():lines.append(f"| {key} | {v['passed']} | {v['entry_without_historical_market_context']} | UNKNOWN | UNKNOWN |")
    lines += ['', 'A=current; B=wick; C=directional close; D=current AND displacement; E=current AND fresh CHOCH; F=wick OR current OR engulfing за CE OR CHOCH за CE. Остальной validate_signal переиспользован через offline AST-копию. Technical proxy использует 80 и частично восстановленный HTF; это не восстановление фактических 18 кандидатов. Исторические market breadth/book/news и полный профиль на каждой секунде недоступны. Поэтому нули Confirmed не подставляются вместо неизвестных исходов.',
    '', '## LIQUIDITY AUDIT','',
    f"Архив: ever sweep={a['liquidity_ever_true']}; ever no-sweep={a['liquidity_ever_false']}; Entry без sweep={a['liquidity_entry_without_sweep']}. Следовательно, 27 — последний срез, а не число прошедших обязательный этап. Liquidity в balanced — информационный фактор, хотя влияет на developing diagnostics.",
    'structure_context сравнивает последнюю свечу с последним подтверждённым swing low/high. Отсутствие sweep здесь не означает отсутствия sweep раньше. Detector не хранит историю снятия liquidity и не знает equal/session/day pools. Причины wrong timeframe/timestamp нельзя приписывать каждому false без доказательств; их статус UNKNOWN, а не установленная ошибка.',
    'Старый expanded detector смешивал high и low в общем списке, затем проверял каждый уровень как оба типа liquidity. Его session window совпадало с коротким local window. Поэтому 1478/362 завышены/методологически непригодны. Новый research использует lows для sell-side и highs для buy-side, отдельные 20/50/288-bar pools, equal levels с допуском 0,1%, предыдущий UTC day и текущую UTC 8-hour session; проверяются только предшествующие уровни.',
    f"В reference-only части старой high-quality expanded группы восстановлено {r['old_high_quality_expanded_rechecked']} зон; корректный typed sweep сохранился у {r['old_high_quality_expanded_correct_sweep']}. Это подмножество reference-only, а не все прежние 362.",
    f"Отдельно перепроверены все прежние 362 (включая production-зоны): {l362}. Для всех 1623 старых Liquidity FAIL: {l}. Детали каждого ID и pool сохранены отдельно.",
    '', '## FVG RECALL','',
    'Фиксированная выборка — те же 3462 reference-only ID из предыдущего snapshot. Предыстория расширена до 350 баров перед formation, чтобы ATR/volume не считались на обрезанных 30 барах. Цифры ниже описывают formation rules: текущую пригодность зоны отдельно определяют age, confirmations и mitigation. Они не сравнимы с 18 ночными entry ID из другого временного окна.',
    f"Первый отказ formation rules: {r['formation_first_failures']}.",f"Качество по независимой причинной классификации: {r['quality']}. A=FVG+size+displacement+typed sweep+structure+known aligned HTF; B=то же без подтверждённого aligned HTF; C=условия этой строгой модели не выполнены. C не доказывает бесполезность.",
    f"Фактический detect_fvgs на полном 350-bar snapshot, с подтверждениями и lifecycle: {diff}. 99 старых reference-only зон принимает неизменённый production detector при полноценном warm-up. Остаток formation PASS объясняется lifecycle либо lookback/confirmation window.",
    f"Idealized detector: {r['idealized_count']} зон, категории {r['idealized_quality']}. HTF UNKNOWN у {r['htf_unknown']} из всей выборки. Отсутствующие HTF нельзя считать opposite.",
    f"152 прежних 'strong body losses': найдено {r['body_152_count']}, quality={r['body_152_quality']}; только body среди проверенных formation-фильтров={r['body_152_only_body_fail']}. Прежнее слово 'только' было ошибочным: тогда считали body FAIL AND ATR>=1, не исключая другие отказы.",
    f"Body/ATR correlation={r['body_atr_pearson']:.4f}; overlap={r['body_atr_overlap']}. Body% измеряет долю тела в диапазоне самой свечи, ATR ratio — размер тела относительно прошлой волатильности. Общий числитель не делает эти фильтры тождественными.",
    f"649 прежних volume primary losses: найдено {r['volume_649_count']}, после восстановления baseline={r['volume_649_recomputed']}. Все reference-only volume states={r['all_volume']}.",
    'Production при fvg_require_volume отвергает not finite baseline. Это подтверждено отдельным unit test. Нормализация volume/20 preceding volumes без impulse в baseline корректна по единицам внутри одного инструмента. Недостающая baseline должна диагностироваться DATA_UNAVAILABLE; пропуск торговли до данных допустим, подмена UNKNOWN на рыночный FAIL — нет. Нельзя суммировать base-volume разных монет; для межрыночных сравнений нужен quote turnover.',
    '', '## SCORE AUDIT','',
    f"Configured={d['runtime']['configured']}; settings loaded={d['runtime']['loaded_settings']}; effective generator={d['runtime']['effective_generator_settings']}; live dashboard/API policies={d['runtime'].get('runtime_values','UNKNOWN')}. Class default=65. Оверрайда Score через environment mapping нет; DB перезаписывает paper_balance, а не score. Scheduler перечитывает тот же JSON и передаёт strategy_settings, сохраняющий порог.",
    f"Оригинальная база имеет несколько исторических policies: {a['policy_windows']}. Это факт, причина переключений по данным не установлена. Пользователь ранее явно выбрал сохранить 80. Все 18 кандидатов: bins={s['bins']}, thresholds={s['thresholds']}. Подробные баллы и восстановимые компоненты: candidate_scores.json; несовпадения окна/компонентов отмечены, не скрыты.",
    '', '## MTF AUDIT','',
    f"17 запрошенных candidate assets, данные срезаны на время исторического решения. Качественные зоны: {m['quality_by_tf']}. Связок 15m→5m и 1h→15m с общей зоной, направлением и causal formation={m['relationships']}. Полные ranking/структура/границы в mtf_ranking.json. Это не охват всех монет, а обеспеченная данными выборка.",
    '', '## FALSE NEGATIVES','',
    f"В causal_replays.json: {c['replay_count']} сетапов, включая BLESSUSDT/MARSCOINUSDT/FARTCOINUSDT и {c['random_replay_count']} случайных ID (seed 6310). Для каждого доступного закрытия сохранены known prefix, реакция, инвалидирование и status. Будущие реакции reference-зон вынесены в future_descriptive_reaction и не участвуют в quality на formation.",
    f"Два исходных случайных ID без OHLC сохранены как UNKNOWN: {c.get('replays_without_bars',[])}. Добавлены два доступных случайных replacement (seed 6311), чтобы были 20 реальных random replays. Excursions следующих 12 баров сохранены отдельно в missed_opportunity_excursions.json; это не PnL.",
    'Это кандидаты на missed opportunities, а не доказанные прибыльные пропуски. Доказать, какой фильтр лучше всего защищает качество, нельзя без сопоставимого out-of-sample outcome после издержек. Более частый геометрический PASS не означает более высокий winrate.',
    '', '## TOP BOTTLENECKS / V6.4 PLAN','',
    'MUST FIX: исследовательские счётчики, сохранение per-call stage outcomes и policy/version; разнести terminal reason и first blocker; warm-up для baseline; типизация liquidity; отделить unavailable от market fail. Production пока не изменён.',
    'SHOULD FIX: после frozen replay сравнить relative orderbook depth и нормализованную дистанцию VWAP как soft quality factors, сохраняя execution cost floors; исторический sweep с ограниченным возрастом; разнести context bonus и invalidation.',
    'OPTIONAL: wick/combination reaction branch, 15m setup→5m entry, 1h→15m, отдельная reversal branch при opposite HTF+MSS. Проверять последовательно на сопоставимых входных данных.',
    'DO NOT TOUCH: closed-candle causality, no look-ahead, full-fill/CE lifecycle действующей гипотезы, валидный SL/TP/RR, издержки и качество обязательных данных. Их прибыльная защитная сила пока не оценена, но отключать их ради числа сигналов оснований нет.',
    'Минимальная исследовательская структура: подтверждённый причинный liquidity sweep → displacement → направленный трёхсвечный FVG → структура → валидная mitigation → объективная закрытая реакция. CONFIRMED дополнительно требует исполнимых цены/риска/стоимости и свежего контекста.',
    'SIGNAL MAY FORM существует как diagnostic output: высокая structure quality и 1–2 отсутствующих условия. UNKNOWN HTF обозначается явно. Это не торговый сигнал. CLI debug: python scripts/critical_rejection_research.py --debug-setup <ID>. Telegram добавлены команды /why_not_signal <ID> и редкие уведомления NEW→IMPROVED→TRIGGER APPROACHING→INVALIDATED; paper trade и signal_outbox они не создают.',
    'Expected effect: исправление отчёта меняет видимость, а не сигнализацию. F/typed liquidity/MTF могут увеличить обнаружение структур; эффект на Confirmed и winrate неизвестен. Risks: больше ложных wick reactions, слишком широкие equal levels, устаревшие sweep, MTF selection bias. Сначала проверка исходов и отдельный shadow dataset, затем решение о V6.4.',
    '', '## Validation','', '33 новых теста rejection/indexing/UNKNOWN volume и 18 существующих pipeline tests пройдены. Дополнительно реальный engine на синтетической последовательности с предшествующим sweep, displacement, FVG и retest при threshold=80 дал Score=95, 1 Confirmed/Generated/Queued/Sent в mock Telegram, 1 paper trade во временной БД, 0 production trades. Результат synthetic_80.json. Сценарии A–F статуса исследовательской модели не означают гарантированного production signal. Production код/настройки не менялись.']
    (OUT/'CRITICAL_RESEARCH_RU.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
if __name__=='__main__':main()

